// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getApp = `-- name: GetApp :one
SELECT id, name, product, api_key_prefix, created_at, last_used_at, revoked_at, created_by FROM apps WHERE id = $1
`

type GetAppRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Product      string     `db:"product" json:"product"`
	ApiKeyPrefix string     `db:"api_key_prefix" json:"api_key_prefix"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	CreatedBy    string     `db:"created_by" json:"created_by"`
}

func (q *Queries) GetApp(ctx context.Context, id uuid.UUID) (GetAppRow, error) {
	row := q.db.QueryRow(ctx, getApp, id)
	var i GetAppRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Product,
		&i.ApiKeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAppByHash = `-- name: GetAppByHash :one
SELECT id, name, product, api_key_prefix, created_at, last_used_at, revoked_at, created_by FROM apps WHERE api_key_hash = $1
`

type GetAppByHashRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Product      string     `db:"product" json:"product"`
	ApiKeyPrefix string     `db:"api_key_prefix" json:"api_key_prefix"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	CreatedBy    string     `db:"created_by" json:"created_by"`
}

func (q *Queries) GetAppByHash(ctx context.Context, apiKeyHash string) (GetAppByHashRow, error) {
	row := q.db.QueryRow(ctx, getAppByHash, apiKeyHash)
	var i GetAppByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Product,
		&i.ApiKeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertApp = `-- name: InsertApp :exec
INSERT INTO apps (id, name, product, api_key_hash, api_key_prefix, created_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAppParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Product      string    `db:"product" json:"product"`
	ApiKeyHash   string    `db:"api_key_hash" json:"api_key_hash"`
	ApiKeyPrefix string    `db:"api_key_prefix" json:"api_key_prefix"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	CreatedBy    string    `db:"created_by" json:"created_by"`
}

func (q *Queries) InsertApp(ctx context.Context, arg InsertAppParams) error {
	_, err := q.db.Exec(ctx, insertApp,
		arg.ID,
		arg.Name,
		arg.Product,
		arg.ApiKeyHash,
		arg.ApiKeyPrefix,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const listApps = `-- name: ListApps :many
SELECT id, name, product, api_key_prefix, created_at, last_used_at, revoked_at, created_by FROM apps ORDER BY created_at DESC
`

type ListAppsRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Product      string     `db:"product" json:"product"`
	ApiKeyPrefix string     `db:"api_key_prefix" json:"api_key_prefix"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	CreatedBy    string     `db:"created_by" json:"created_by"`
}

func (q *Queries) ListApps(ctx context.Context) ([]ListAppsRow, error) {
	rows, err := q.db.Query(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppsRow
	for rows.Next() {
		var i ListAppsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Product,
			&i.ApiKeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApp = `-- name: RevokeApp :exec
UPDATE apps SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeApp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeApp, id)
	return err
}

const updateAppKeyHash = `-- name: UpdateAppKeyHash :exec
UPDATE apps SET api_key_hash = $2, api_key_prefix = $3 WHERE id = $1
`

type UpdateAppKeyHashParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	ApiKeyHash   string    `db:"api_key_hash" json:"api_key_hash"`
	ApiKeyPrefix string    `db:"api_key_prefix" json:"api_key_prefix"`
}

func (q *Queries) UpdateAppKeyHash(ctx context.Context, arg UpdateAppKeyHashParams) error {
	_, err := q.db.Exec(ctx, updateAppKeyHash, arg.ID, arg.ApiKeyHash, arg.ApiKeyPrefix)
	return err
}
