// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_events.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const claimGatewayEventsForDispatch = `-- name: ClaimGatewayEventsForDispatch :many
SELECT id, ref, gateway, status, raw_request, raw_response, created_at FROM gateway_events
WHERE status = 'pending' ORDER BY created_at LIMIT $1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimGatewayEventsForDispatch(ctx context.Context, limit int32) ([]GatewayEvent, error) {
	rows, err := q.db.Query(ctx, claimGatewayEventsForDispatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayEvent
	for rows.Next() {
		var i GatewayEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.Gateway,
			&i.Status,
			&i.RawRequest,
			&i.RawResponse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGatewayEvent = `-- name: InsertGatewayEvent :exec
INSERT INTO gateway_events (id, ref, gateway, status, raw_request, raw_response, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
`

type InsertGatewayEventParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Ref         string    `db:"ref" json:"ref"`
	Gateway     string    `db:"gateway" json:"gateway"`
	Status      string    `db:"status" json:"status"`
	RawRequest  []byte    `db:"raw_request" json:"raw_request"`
	RawResponse []byte    `db:"raw_response" json:"raw_response"`
}

func (q *Queries) InsertGatewayEvent(ctx context.Context, arg InsertGatewayEventParams) error {
	_, err := q.db.Exec(ctx, insertGatewayEvent,
		arg.ID,
		arg.Ref,
		arg.Gateway,
		arg.Status,
		arg.RawRequest,
		arg.RawResponse,
	)
	return err
}

const listGatewayEvents = `-- name: ListGatewayEvents :many
SELECT id, ref, gateway, status, raw_request, raw_response, created_at FROM gateway_events WHERE ref = $1 ORDER BY created_at
`

func (q *Queries) ListGatewayEvents(ctx context.Context, ref string) ([]GatewayEvent, error) {
	rows, err := q.db.Query(ctx, listGatewayEvents, ref)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayEvent
	for rows.Next() {
		var i GatewayEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.Gateway,
			&i.Status,
			&i.RawRequest,
			&i.RawResponse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
