// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger_entries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (id, kind, ref, amount_pesewas, currency, value_time, booking_time, settlement_time, product, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
`

type InsertLedgerEntryParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	Kind           string     `db:"kind" json:"kind"`
	Ref            string     `db:"ref" json:"ref"`
	AmountPesewas  int64      `db:"amount_pesewas" json:"amount_pesewas"`
	Currency       string     `db:"currency" json:"currency"`
	ValueTime      time.Time  `db:"value_time" json:"value_time"`
	BookingTime    time.Time  `db:"booking_time" json:"booking_time"`
	SettlementTime *time.Time `db:"settlement_time" json:"settlement_time"`
	Product        string     `db:"product" json:"product"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.Kind,
		arg.Ref,
		arg.AmountPesewas,
		arg.Currency,
		arg.ValueTime,
		arg.BookingTime,
		arg.SettlementTime,
		arg.Product,
	)
	return err
}

const listLedgerEntriesByRef = `-- name: ListLedgerEntriesByRef :many
SELECT id, kind, ref, amount_pesewas, currency, value_time, booking_time, settlement_time, product, created_at
FROM ledger_entries WHERE ref = $1 ORDER BY booking_time
`

func (q *Queries) ListLedgerEntriesByRef(ctx context.Context, ref string) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByRef, ref)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Ref,
			&i.AmountPesewas,
			&i.Currency,
			&i.ValueTime,
			&i.BookingTime,
			&i.SettlementTime,
			&i.Product,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampLedgerSettlement = `-- name: StampLedgerSettlement :execrows
UPDATE ledger_entries SET settlement_time = $2
WHERE ref = $1 AND settlement_time IS NULL
`

type StampLedgerSettlementParams struct {
	Ref            string     `db:"ref" json:"ref"`
	SettlementTime *time.Time `db:"settlement_time" json:"settlement_time"`
}

func (q *Queries) StampLedgerSettlement(ctx context.Context, arg StampLedgerSettlementParams) (int64, error) {
	result, err := q.db.Exec(ctx, stampLedgerSettlement, arg.Ref, arg.SettlementTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLedgerEntrySettlement = `-- name: UpdateLedgerEntrySettlement :execrows
UPDATE ledger_entries SET settlement_time = $3 WHERE id = $1 AND settlement_time IS NULL AND $2::text IS NOT NULL
`

type UpdateLedgerEntrySettlementParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	Column2        string     `db:"column_2" json:"column_2"`
	SettlementTime *time.Time `db:"settlement_time" json:"settlement_time"`
}

func (q *Queries) UpdateLedgerEntrySettlement(ctx context.Context, arg UpdateLedgerEntrySettlementParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLedgerEntrySettlement, arg.ID, arg.Column2, arg.SettlementTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
