// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Product      string     `db:"product" json:"product"`
	ApiKeyHash   string     `db:"api_key_hash" json:"api_key_hash"`
	ApiKeyPrefix string     `db:"api_key_prefix" json:"api_key_prefix"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	CreatedBy    string     `db:"created_by" json:"created_by"`
}

type GatewayEvent struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Ref         string    `db:"ref" json:"ref"`
	Gateway     string    `db:"gateway" json:"gateway"`
	Status      string    `db:"status" json:"status"`
	RawRequest  []byte    `db:"raw_request" json:"raw_request"`
	RawResponse []byte    `db:"raw_response" json:"raw_response"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type LedgerEntry struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	Kind           string     `db:"kind" json:"kind"`
	Ref            string     `db:"ref" json:"ref"`
	AmountPesewas  int64      `db:"amount_pesewas" json:"amount_pesewas"`
	Currency       string     `db:"currency" json:"currency"`
	ValueTime      time.Time  `db:"value_time" json:"value_time"`
	BookingTime    time.Time  `db:"booking_time" json:"booking_time"`
	SettlementTime *time.Time `db:"settlement_time" json:"settlement_time"`
	Product        string     `db:"product" json:"product"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
}

type PaymentIntent struct {
	Ref              string      `db:"ref" json:"ref"`
	Product          string      `db:"product" json:"product"`
	Gateway          string      `db:"gateway" json:"gateway"`
	AmountPesewas    int64       `db:"amount_pesewas" json:"amount_pesewas"`
	Currency         string      `db:"currency" json:"currency"`
	Wallet           pgtype.Text `db:"wallet" json:"wallet"`
	IdempotencyKey   pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
	Status           string      `db:"status" json:"status"`
	AuthorizationURL pgtype.Text `db:"authorization_url" json:"authorization_url"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
}

type PayoutBatch struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	Product        string      `db:"product" json:"product"`
	TotalPesewas   int64       `db:"total_pesewas" json:"total_pesewas"`
	Currency       string      `db:"currency" json:"currency"`
	Status         string      `db:"status" json:"status"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
	BatchDate      time.Time   `db:"batch_date" json:"batch_date"`
	IdempotencyKey pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
}

type PayoutReservation struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	BatchID       uuid.UUID   `db:"batch_id" json:"batch_id"`
	AmountPesewas int64       `db:"amount_pesewas" json:"amount_pesewas"`
	Currency      string      `db:"currency" json:"currency"`
	Status        string      `db:"status" json:"status"`
	SettledAt     *time.Time  `db:"settled_at" json:"settled_at"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	Recipient     pgtype.Text `db:"recipient" json:"recipient"`
	Reference     pgtype.Text `db:"reference" json:"reference"`
	Gateway       pgtype.Text `db:"gateway" json:"gateway"`
}

type PlatformCommissionEntry struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	Ref            string     `db:"ref" json:"ref"`
	AmountPesewas  int64      `db:"amount_pesewas" json:"amount_pesewas"`
	Currency       string     `db:"currency" json:"currency"`
	ValueTime      time.Time  `db:"value_time" json:"value_time"`
	BookingTime    time.Time  `db:"booking_time" json:"booking_time"`
	SettlementTime *time.Time `db:"settlement_time" json:"settlement_time"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
}

type VendorLedgerEntry struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	VendorID       *uuid.UUID `db:"vendor_id" json:"vendor_id"`
	Ref            string     `db:"ref" json:"ref"`
	AmountPesewas  int64      `db:"amount_pesewas" json:"amount_pesewas"`
	Currency       string     `db:"currency" json:"currency"`
	ValueTime      time.Time  `db:"value_time" json:"value_time"`
	BookingTime    time.Time  `db:"booking_time" json:"booking_time"`
	SettlementTime *time.Time `db:"settlement_time" json:"settlement_time"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
}

type WebhookInbox struct {
	AggregatorEventID string     `db:"aggregator_event_id" json:"aggregator_event_id"`
	Gateway           string     `db:"gateway" json:"gateway"`
	Payload           []byte     `db:"payload" json:"payload"`
	ReceivedAt        time.Time  `db:"received_at" json:"received_at"`
	ProcessedAt       *time.Time `db:"processed_at" json:"processed_at"`
}
