// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_intents.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentIntent = `-- name: CreatePaymentIntent :exec
INSERT INTO payment_intents (ref, product, gateway, amount_pesewas, currency, wallet, idempotency_key, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
`

type CreatePaymentIntentParams struct {
	Ref            string      `db:"ref" json:"ref"`
	Product        string      `db:"product" json:"product"`
	Gateway        string      `db:"gateway" json:"gateway"`
	AmountPesewas  int64       `db:"amount_pesewas" json:"amount_pesewas"`
	Currency       string      `db:"currency" json:"currency"`
	Wallet         pgtype.Text `db:"wallet" json:"wallet"`
	IdempotencyKey pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
	Status         string      `db:"status" json:"status"`
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) error {
	_, err := q.db.Exec(ctx, createPaymentIntent,
		arg.Ref,
		arg.Product,
		arg.Gateway,
		arg.AmountPesewas,
		arg.Currency,
		arg.Wallet,
		arg.IdempotencyKey,
		arg.Status,
	)
	return err
}

const getPaymentIntentByIdempotencyKey = `-- name: GetPaymentIntentByIdempotencyKey :one
SELECT ref FROM payment_intents WHERE product = $1 AND idempotency_key = $2
`

type GetPaymentIntentByIdempotencyKeyParams struct {
	Product        string      `db:"product" json:"product"`
	IdempotencyKey pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetPaymentIntentByIdempotencyKey(ctx context.Context, arg GetPaymentIntentByIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByIdempotencyKey, arg.Product, arg.IdempotencyKey)
	var ref string
	err := row.Scan(&ref)
	return ref, err
}

const getPaymentIntentByRef = `-- name: GetPaymentIntentByRef :one
SELECT ref, product, gateway, amount_pesewas, currency, wallet, idempotency_key, status, created_at
FROM payment_intents WHERE ref = $1
`

func (q *Queries) GetPaymentIntentByRef(ctx context.Context, ref string) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByRef, ref)
	var i PaymentIntent
	err := row.Scan(
		&i.Ref,
		&i.Product,
		&i.Gateway,
		&i.AmountPesewas,
		&i.Currency,
		&i.Wallet,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentIntentForWebhook = `-- name: GetPaymentIntentForWebhook :one
SELECT ref, gateway, status, product FROM payment_intents WHERE ref = $1
`

type GetPaymentIntentForWebhookRow struct {
	Ref     string `db:"ref" json:"ref"`
	Gateway string `db:"gateway" json:"gateway"`
	Status  string `db:"status" json:"status"`
	Product string `db:"product" json:"product"`
}

func (q *Queries) GetPaymentIntentForWebhook(ctx context.Context, ref string) (GetPaymentIntentForWebhookRow, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentForWebhook, ref)
	var i GetPaymentIntentForWebhookRow
	err := row.Scan(
		&i.Ref,
		&i.Gateway,
		&i.Status,
		&i.Product,
	)
	return i, err
}

const getPaymentIntentStatus = `-- name: GetPaymentIntentStatus :one
SELECT status FROM payment_intents WHERE ref = $1
`

func (q *Queries) GetPaymentIntentStatus(ctx context.Context, ref string) (string, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentStatus, ref)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updatePaymentIntentStatus = `-- name: UpdatePaymentIntentStatus :exec
UPDATE payment_intents SET status = $2 WHERE ref = $1
`

type UpdatePaymentIntentStatusParams struct {
	Ref    string `db:"ref" json:"ref"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdatePaymentIntentStatus(ctx context.Context, arg UpdatePaymentIntentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentStatus, arg.Ref, arg.Status)
	return err
}
