// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payout_reservations.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayoutBatch = `-- name: CreatePayoutBatch :exec
INSERT INTO payout_batches (id, product, total_pesewas, currency, status, batch_date, idempotency_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
`

type CreatePayoutBatchParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	Product        string      `db:"product" json:"product"`
	TotalPesewas   int64       `db:"total_pesewas" json:"total_pesewas"`
	Currency       string      `db:"currency" json:"currency"`
	Status         string      `db:"status" json:"status"`
	BatchDate      time.Time   `db:"batch_date" json:"batch_date"`
	IdempotencyKey pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) CreatePayoutBatch(ctx context.Context, arg CreatePayoutBatchParams) error {
	_, err := q.db.Exec(ctx, createPayoutBatch,
		arg.ID,
		arg.Product,
		arg.TotalPesewas,
		arg.Currency,
		arg.Status,
		arg.BatchDate,
		arg.IdempotencyKey,
	)
	return err
}

const createPayoutReservation = `-- name: CreatePayoutReservation :exec
INSERT INTO payout_reservations (id, batch_id, amount_pesewas, currency, status, recipient, reference, gateway, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
`

type CreatePayoutReservationParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	BatchID       uuid.UUID   `db:"batch_id" json:"batch_id"`
	AmountPesewas int64       `db:"amount_pesewas" json:"amount_pesewas"`
	Currency      string      `db:"currency" json:"currency"`
	Status        string      `db:"status" json:"status"`
	Recipient     pgtype.Text `db:"recipient" json:"recipient"`
	Reference     pgtype.Text `db:"reference" json:"reference"`
	Gateway       pgtype.Text `db:"gateway" json:"gateway"`
}

func (q *Queries) CreatePayoutReservation(ctx context.Context, arg CreatePayoutReservationParams) error {
	_, err := q.db.Exec(ctx, createPayoutReservation,
		arg.ID,
		arg.BatchID,
		arg.AmountPesewas,
		arg.Currency,
		arg.Status,
		arg.Recipient,
		arg.Reference,
		arg.Gateway,
	)
	return err
}

const getPayoutBatch = `-- name: GetPayoutBatch :one
SELECT id, product, total_pesewas, currency, status, batch_date, idempotency_key, created_at
FROM payout_batches WHERE id = $1
`

type GetPayoutBatchRow struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	Product        string      `db:"product" json:"product"`
	TotalPesewas   int64       `db:"total_pesewas" json:"total_pesewas"`
	Currency       string      `db:"currency" json:"currency"`
	Status         string      `db:"status" json:"status"`
	BatchDate      time.Time   `db:"batch_date" json:"batch_date"`
	IdempotencyKey pgtype.Text `db:"idempotency_key" json:"idempotency_key"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPayoutBatch(ctx context.Context, id uuid.UUID) (GetPayoutBatchRow, error) {
	row := q.db.QueryRow(ctx, getPayoutBatch, id)
	var i GetPayoutBatchRow
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.TotalPesewas,
		&i.Currency,
		&i.Status,
		&i.BatchDate,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutReservationByID = `-- name: GetPayoutReservationByID :one
SELECT id, batch_id, amount_pesewas, currency, status, recipient, reference, gateway, settled_at, created_at
FROM payout_reservations WHERE id = $1
`

type GetPayoutReservationByIDRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	BatchID       uuid.UUID   `db:"batch_id" json:"batch_id"`
	AmountPesewas int64       `db:"amount_pesewas" json:"amount_pesewas"`
	Currency      string      `db:"currency" json:"currency"`
	Status        string      `db:"status" json:"status"`
	Recipient     pgtype.Text `db:"recipient" json:"recipient"`
	Reference     pgtype.Text `db:"reference" json:"reference"`
	Gateway       pgtype.Text `db:"gateway" json:"gateway"`
	SettledAt     *time.Time  `db:"settled_at" json:"settled_at"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPayoutReservationByID(ctx context.Context, id uuid.UUID) (GetPayoutReservationByIDRow, error) {
	row := q.db.QueryRow(ctx, getPayoutReservationByID, id)
	var i GetPayoutReservationByIDRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.AmountPesewas,
		&i.Currency,
		&i.Status,
		&i.Recipient,
		&i.Reference,
		&i.Gateway,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPayoutReservationsByBatch = `-- name: ListPayoutReservationsByBatch :many
SELECT id, batch_id, amount_pesewas, currency, status, recipient, reference, gateway, settled_at, created_at
FROM payout_reservations WHERE batch_id = $1 ORDER BY created_at
`

type ListPayoutReservationsByBatchRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	BatchID       uuid.UUID   `db:"batch_id" json:"batch_id"`
	AmountPesewas int64       `db:"amount_pesewas" json:"amount_pesewas"`
	Currency      string      `db:"currency" json:"currency"`
	Status        string      `db:"status" json:"status"`
	Recipient     pgtype.Text `db:"recipient" json:"recipient"`
	Reference     pgtype.Text `db:"reference" json:"reference"`
	Gateway       pgtype.Text `db:"gateway" json:"gateway"`
	SettledAt     *time.Time  `db:"settled_at" json:"settled_at"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) ListPayoutReservationsByBatch(ctx context.Context, batchID uuid.UUID) ([]ListPayoutReservationsByBatchRow, error) {
	rows, err := q.db.Query(ctx, listPayoutReservationsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayoutReservationsByBatchRow
	for rows.Next() {
		var i ListPayoutReservationsByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.AmountPesewas,
			&i.Currency,
			&i.Status,
			&i.Recipient,
			&i.Reference,
			&i.Gateway,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePayoutReservation = `-- name: ReleasePayoutReservation :execrows
UPDATE payout_reservations SET status = 'released' WHERE id = $1 AND status = 'open'
`

func (q *Queries) ReleasePayoutReservation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releasePayoutReservation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settlePayoutReservation = `-- name: SettlePayoutReservation :execrows
UPDATE payout_reservations SET status = 'settled', settled_at = $2 WHERE id = $1 AND status = 'open'
`

type SettlePayoutReservationParams struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	SettledAt *time.Time `db:"settled_at" json:"settled_at"`
}

func (q *Queries) SettlePayoutReservation(ctx context.Context, arg SettlePayoutReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, settlePayoutReservation, arg.ID, arg.SettledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
