// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimGatewayEventsForDispatch(ctx context.Context, limit int32) ([]GatewayEvent, error)
	CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) error
	CreatePayoutBatch(ctx context.Context, arg CreatePayoutBatchParams) error
	CreatePayoutReservation(ctx context.Context, arg CreatePayoutReservationParams) error
	DeleteWebhookInbox(ctx context.Context, aggregatorEventID string) (int64, error)
	ExistsWebhookInbox(ctx context.Context, aggregatorEventID string) (bool, error)
	GetApp(ctx context.Context, id uuid.UUID) (GetAppRow, error)
	GetAppByHash(ctx context.Context, apiKeyHash string) (GetAppByHashRow, error)
	GetPaymentIntentByIdempotencyKey(ctx context.Context, arg GetPaymentIntentByIdempotencyKeyParams) (string, error)
	GetPaymentIntentByRef(ctx context.Context, ref string) (PaymentIntent, error)
	GetPaymentIntentForWebhook(ctx context.Context, ref string) (GetPaymentIntentForWebhookRow, error)
	GetPaymentIntentStatus(ctx context.Context, ref string) (string, error)
	GetPayoutBatch(ctx context.Context, id uuid.UUID) (GetPayoutBatchRow, error)
	GetPayoutReservationByID(ctx context.Context, id uuid.UUID) (GetPayoutReservationByIDRow, error)
	InsertApp(ctx context.Context, arg InsertAppParams) error
	InsertGatewayEvent(ctx context.Context, arg InsertGatewayEventParams) error
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error
	InsertWebhookInbox(ctx context.Context, arg InsertWebhookInboxParams) error
	InsertWebhookInboxDedup(ctx context.Context, arg InsertWebhookInboxDedupParams) (int64, error)
	ListApps(ctx context.Context) ([]ListAppsRow, error)
	ListGatewayEvents(ctx context.Context, ref string) ([]GatewayEvent, error)
	ListLedgerEntriesByRef(ctx context.Context, ref string) ([]LedgerEntry, error)
	ListPayoutReservationsByBatch(ctx context.Context, batchID uuid.UUID) ([]ListPayoutReservationsByBatchRow, error)
	ReleasePayoutReservation(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeApp(ctx context.Context, id uuid.UUID) error
	SettlePayoutReservation(ctx context.Context, arg SettlePayoutReservationParams) (int64, error)
	StampLedgerSettlement(ctx context.Context, arg StampLedgerSettlementParams) (int64, error)
	UpdateAppKeyHash(ctx context.Context, arg UpdateAppKeyHashParams) error
	UpdateLedgerEntrySettlement(ctx context.Context, arg UpdateLedgerEntrySettlementParams) (int64, error)
	UpdatePaymentIntentStatus(ctx context.Context, arg UpdatePaymentIntentStatusParams) error
}

var _ Querier = (*Queries)(nil)
