// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_inbox.sql

package postgres

import (
	"context"
)

const deleteWebhookInbox = `-- name: DeleteWebhookInbox :execrows
DELETE FROM webhook_inbox WHERE aggregator_event_id = $1
`

func (q *Queries) DeleteWebhookInbox(ctx context.Context, aggregatorEventID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookInbox, aggregatorEventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsWebhookInbox = `-- name: ExistsWebhookInbox :one
SELECT EXISTS(SELECT 1 FROM webhook_inbox WHERE aggregator_event_id = $1)
`

func (q *Queries) ExistsWebhookInbox(ctx context.Context, aggregatorEventID string) (bool, error) {
	row := q.db.QueryRow(ctx, existsWebhookInbox, aggregatorEventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertWebhookInbox = `-- name: InsertWebhookInbox :exec
INSERT INTO webhook_inbox (aggregator_event_id, gateway, payload, received_at)
VALUES ($1, $2, $3, now())
`

type InsertWebhookInboxParams struct {
	AggregatorEventID string `db:"aggregator_event_id" json:"aggregator_event_id"`
	Gateway           string `db:"gateway" json:"gateway"`
	Payload           []byte `db:"payload" json:"payload"`
}

func (q *Queries) InsertWebhookInbox(ctx context.Context, arg InsertWebhookInboxParams) error {
	_, err := q.db.Exec(ctx, insertWebhookInbox, arg.AggregatorEventID, arg.Gateway, arg.Payload)
	return err
}

const insertWebhookInboxDedup = `-- name: InsertWebhookInboxDedup :execrows
INSERT INTO webhook_inbox (aggregator_event_id, gateway, payload, received_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (aggregator_event_id) DO NOTHING
`

type InsertWebhookInboxDedupParams struct {
	AggregatorEventID string `db:"aggregator_event_id" json:"aggregator_event_id"`
	Gateway           string `db:"gateway" json:"gateway"`
	Payload           []byte `db:"payload" json:"payload"`
}

func (q *Queries) InsertWebhookInboxDedup(ctx context.Context, arg InsertWebhookInboxDedupParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookInboxDedup, arg.AggregatorEventID, arg.Gateway, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
